import fs from 'node:fs/promises';
import path from 'node:path';
import chalk from 'chalk';
import inquirer from 'inquirer';

export async function initCommand(): Promise<void> {
  console.log(chalk.cyan('\n  ⚡ Initializing CL8...\n'));

  const answers = await inquirer.prompt([
    {
      type: 'list',
      name: 'provider',
      message: 'Default AI provider:',
      choices: [
        { name: 'OpenAI', value: 'openai' },
        { name: 'Google Gemini', value: 'gemini' },
        { name: 'Ollama (local)', value: 'ollama' },
      ],
    },
    {
      type: 'input',
      name: 'apiKey',
      message: 'API key (leave blank for Ollama):',
      when: (answers) => answers.provider !== 'ollama',
    },
    {
      type: 'list',
      name: 'approvalMode',
      message: 'Command approval mode:',
      choices: [
        { name: 'Ask before each command (recommended)', value: 'ask' },
        { name: 'Auto-approve safe commands', value: 'auto' },
        { name: 'Deny all command execution', value: 'deny' },
      ],
    },
    {
      type: 'input',
      name: 'workspace',
      message: 'Workspace directory:',
      default: process.cwd(),
    },
  ]);

  const envContent = `# CL8 Configuration
# Generated by \`cl8 init\`

${answers.provider === 'openai' ? `OPENAI_API_KEY=${answers.apiKey || ''}
OPENAI_MODEL=gpt-4o` : ''}
${answers.provider === 'gemini' ? `GEMINI_API_KEY=${answers.apiKey || ''}
GEMINI_MODEL=gemini-2.0-flash` : ''}
${answers.provider === 'ollama' ? `OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_MODEL=codellama` : ''}

CL8_DEFAULT_PROVIDER=${answers.provider}
CL8_WORKSPACE=${answers.workspace}
CL8_APPROVAL_MODE=${answers.approvalMode}
CL8_LOG_LEVEL=info
`;

  const envPath = path.resolve(process.cwd(), '.env');

  try {
    const exists = await fs.access(envPath).then(() => true).catch(() => false);
    if (exists) {
      const { overwrite } = await inquirer.prompt([
        {
          type: 'confirm',
          name: 'overwrite',
          message: '.env file already exists. Overwrite?',
          default: false,
        },
      ]);
      if (!overwrite) {
        console.log(chalk.yellow('\n  ✋ Initialization cancelled.\n'));
        return;
      }
    }

    await fs.writeFile(envPath, envContent, 'utf-8');
    console.log(chalk.green(`\n  ✅ Configuration written to ${chalk.bold('.env')}\n`));
    console.log(chalk.cyan('  Next steps:'));
    console.log(chalk.dim('    1. Edit .env with your API keys'));
    console.log(chalk.dim('    2. Run `cl8` to start chatting'));
    console.log('');
  } catch (err) {
    console.error(chalk.red(`\n  ✖ Failed to write .env: ${err}\n`));
  }
}
